{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allured.py:14: AssertionError"}, "description": "this test fails", "start": 1616058300336, "stop": 1616058300336, "uuid": "a67229ac-68fd-4046-a964-17198893a9a3", "historyId": "caea8814866f0edda4a043a391cfed17", "testCaseId": "b332f92e7a20596e04bddc6a3f9e7fcf", "fullName": "test_allured#test_failure", "labels": [{"name": "suite", "value": "test_allured"}, {"name": "host", "value": "gioddeMacBook-Pro.local"}, {"name": "thread", "value": "98272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allured"}]}